### ISSUE TITLE
GetPassWarning: Can not control echo on the terminal.

### ISSUE THREAD

**Issue by vungsung** [D4Vinci/Cr3dOv3r#24]
Either in Python 2.7 nether in Python 3.6 has the problem.
The Logs:

////////////////////////////////////////////////////////////////////////////////////////////////////////

[+] Checking email in public leaks...

Results found : 1
---------------------------------------
      Name of leak => Dropbox
      Date of leakage => 2012-07-14T00:00:00+00:00
      Details => https://hacked-emails.com/leak/anon-dropbox68m2012txt

C:\Python27amd64\lib\getpass.py:92: GetPassWarning: Can not control echo on the terminal.
  return fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Please enter the password=> 

////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by D4Vinci** [comment]
You are on windows right ?

**Comment by Abdulla-B** [comment]
I'm facing the same issue and I'm on Windows

**Comment by vungsung** [comment]
I was on Windows.
Kali Linux doesn't pop up the error.
Thanks for reply.

**Comment by Abdulla-B** [comment]
I'm still facing the issue so please let me know if you'd like me to start another thread @D4Vinci and thank you for your hard work

**Comment by D4Vinci** [comment]
I'will fix it for windows in the next update just wait for it

**Comment by Joulain** [comment]
Might be me, but i got the latest update available at the moment :
(PyCharm 2018.3.5 Community Edition
Build #PC-183.5912.18, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
python 3.6.6)

Might be a special problem on me but it work perfectly on my cmd but absolutly not on the default run of pycharm that I use.

Anyway, please tell me if the problem is handled or not
